asyncapi: 3.0.0
id: 'urn:io.microcks.example.user-signedup'
info:
  title: User signed-up API
  version: 0.3.0
  description: Sample AsyncAPI for user signedup events
  contact:
    name: Laurent Broudoux
    url: https://github.com/lbroudoux
    email: laurent@microcks.io
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
defaultContentType: application/json
channels:
  user-signedupout:
    description: The topic on which user signed up or out events may be consumed
    messages:
      userSignedUp:
        $ref: '#/components/messages/userSignedUp'
      userSignedOut:
        $ref: '#/components/messages/userSignedOut'
operations:
  publishUserSignedUpOut:
    action: 'send'
    channel:
      $ref: '#/channels/user-signedupout'
    summary: Receive information about user signed up or out
    messages:
      - $ref: '#/channels/user-signedupout/messages/userSignedUp'
      - $ref: '#/channels/user-signedupout/messages/userSignedOut'
components:
  messages:
    userSignedUp:
      description: An event describing that a user just signed up
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      headers:
        type: object
        properties:
          sentAt:
            type: string
            format: date-time
            description: Date and time when the event was sent
      payload:
        type: object
        additionalProperties: false
        properties:
          fullName:
            type: string
          email:
            type: string
            format: email
          age:
            type: integer
            minimum: 18
      examples:
        - name: laurent
          summary: Example for Laurent user
          headers:
            my-app-header: 23
            sentAt: "2020-03-11T08:03:28Z"
          payload:
            fullName: Laurent Broudoux
            email: "laurent@microcks.io"
            age: 41
        - name: john
          summary: Example for John Doe user
          headers:
            my-app-header: 24
            sentAt: "2020-03-11T08:03:38Z"
          payload:
            fullName: John Doe
            email: john@microcks.io
            age: 36
    userSignedOut:
      description: An event describing that a user just signed out
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      headers:
        type: object
        properties:
          sentAt:
            type: string
            format: date-time
            description: Date and time when the event was sent
      payload:
        type: object
        additionalProperties: false
        properties:
          id:
            type: string
      examples:
        - name: laurent
          summary: Example for Laurent user
          headers:
            my-app-header: 23
            sentAt: "2024-02-06T08:02:38Z"
          payload:
            id: c62a2b1e-0dfc-44b5-88cc-9aba252a1368
        - name: john
          summary: Example for John Doe user
          headers:
            my-app-header: 24
            sentAt: "2024-02-06T08:03:38Z"
          payload:
            id: dc38d465-bbeb-4fab-a84d-6cff46394716
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          my-app-header:
            type: integer
            minimum: 0
            maximum: 100
      examples:
        - laurent:
            my-app-header: 21
        - yacine:
            my-app-header: 22